### ISSUE TITLE
Problem building "buddy project"

### ISSUE THREAD

**Issue by poserdonut** [rr-wfm/MSBuild.Sdk.SqlProj#106]
Hi!

I'm trying to use a buddy project to build my sql projects. 

The buddy project has this csproj file. 

```
<Project Sdk="MSBuild.Sdk.SqlProj/1.10.0">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Insurance/Insurance.sqlproj" DatabaseVariableLiteralValue="Insurance" />
  </ItemGroup>

</Project>
```

![image](https://user-images.githubusercontent.com/61051475/102584823-7a750d00-4107-11eb-81d7-91e84298b7d8.png)

There is an Insurance.dacpac file being. 

However when running build on the buddy project I get the following error. 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "dotnet "C:\Users\FJBE85\.nuget\packages\msbuild.sdk.sqlproj\1.10.0\Sdk\../tools/netcoreapp5.0/DacpacTool.dll" build -o "obj\Debug\netstandard2.0\KPP.JuridiskPerson.Database.Build.dacpac" -n "KPP.JuridiskPerson.Database.Build" -v "1.0.0" -sv Sql150 -i "obj\Debug\netstandard2.0\KPP.JuridiskPerson.Database.Build.InputFiles.txt" -r "C:\git\kpp-juridiskperson-service\KPP.JuridiskPerson.Service\Databas\Insurance\bin\Debug\Insurance.dll;Insurance"      " exited with code 1.	KPP.JuridiskPerson.Database.Build	C:\Users\FJBE85\.nuget\packages\msbuild.sdk.sqlproj\1.10.0\Sdk\Sdk.targets	196	
```

So I tried copying the command line for the build into powershell and running it. 

```
PS C:\Users\FJBE85> dotnet "C:\Users\FJBE85\.nuget\packages\msbuild.sdk.sqlproj\1.10.0\Sdk\../tools/netcoreapp5.0/DacpacTool.dll" build -o "obj\Debug\netstandard2.0\KPP.JuridiskPerson.Database.Build.dacpac" -n "KP
P.JuridiskPerson.Database.Build" -v "1.0.0" -sv Sql150 -i "obj\Debug\netstandard2.0\KPP.JuridiskPerson.Database.Build.InputFiles.txt" -r "C:\git\kpp-juridiskperson-service\KPP.JuridiskPerson.Service\Databas\Insura
nce\bin\Debug\Insurance.dll;Insurance"
Using package name KPP.JuridiskPerson.Database.Build and version 1.0.0
Using SQL Server version Sql150
Adding reference to C:\git\kpp-juridiskperson-service\KPP.JuridiskPerson.Service\Databas\Insurance\bin\Debug\Insurance.dll with external parts Insurance
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModelException: Failed to load C:\git\kpp-juridiskperson-service\KPP.JuridiskPerson.Service\Databas\Insurance\bin\Debug\Insurance.dll.
 ---> Microsoft.Data.Tools.Schema.Sql.Build.SqlPackageException: End of Central Directory record could not be found.
 ---> System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at Microsoft.Data.Tools.Schema.Sql.Packaging.ZipPackage..ctor(String path, FileMode packageFileMode, FileAccess packageFileAccess, FileShare share)
   at Microsoft.Data.Tools.Schema.Sql.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare)
   at Microsoft.Data.Tools.Schema.Sql.Build.SqlPackage.Artifact.InitializefromFile(FileInfo fileInfo, FileMode mode, FileAccess access)
   --- End of inner exception stack trace ---
   at Microsoft.Data.Tools.Schema.Sql.Build.SqlPackage.Artifact.InitializefromFile(FileInfo fileInfo, FileMode mode, FileAccess access)
   at Microsoft.Data.Tools.Schema.Sql.Build.SqlPackage.Artifact..ctor(FileInfo fileInfo, FileAccess access)
   at Microsoft.Data.Tools.Schema.Sql.Build.SqlPackage.Open(FileInfo fileInfo, FileAccess access)
   at Microsoft.Data.Tools.Schema.Sql.Build.SqlPackage.Open(String file, FileAccess access)
   at Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModel.AddReference(CustomSchemaData customData)
   --- End of inner exception stack trace ---
   at Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModel.ThrowReferenceLoadingException(Exception innerException, String fileName)
   at Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModel.AddReference(CustomSchemaData customData)
   at Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModel.OnCustomDataAdded(CustomSchemaData customData)
   at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlSchemaModel.OnCustomDataAdded(CustomSchemaData customData)
   at Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModel.AddCustomData(CustomSchemaData customData, Boolean raiseEvents)
   at Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModel.AddCustomData(CustomSchemaData customData)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MSBuild.Sdk.SqlProj.DacpacTool.Extensions.AddCustomData(Object dataSchemaModel, Object customData) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Extensions.cs:line 77
   at MSBuild.Sdk.SqlProj.DacpacTool.Extensions.AddReference(TSqlModel model, String referencePath, String externalParts) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Extensions.cs:line 27
   at MSBuild.Sdk.SqlProj.DacpacTool.PackageBuilder.AddExternalReference(String referenceFile, String externalParts) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/PackageBuilder.cs:line 50
   at MSBuild.Sdk.SqlProj.DacpacTool.Program.BuildDacpac(BuildOptions options) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Program.cs:line 102
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

And I can't really figure out why it's not working.

**Comment by ErikEJ** [comment]
You should not reference the .sqlproj

**Comment by poserdonut** [comment]
Oh, so I misunderstood the project reference stuff. 

Does this mean if I have several different databases (sql projects) I will need a buddy build project for each of them?

**Comment by jmezach** [comment]
Project references only work with other projects that use `MSBuild.Sdk.SqlProj` yes. You can't add a project reference to a `.sqlproj`.

**Comment by poserdonut** [comment]
OK, thank you for the quick responses.
