### ISSUE TITLE
dotnet build error: Only one statement is allowed per batch. A batch separator, such as 'GO', might be required between statements.

### ISSUE THREAD

**Issue by artazar** [rr-wfm/MSBuild.Sdk.SqlProj#122]
Hi,

Thank you for the project, I am looking into adapting it for existing SSDT projects pipelines and moving them into dotnet core.

I have done a very simple thing and get the following error, can you help me?

1. Forked the repository: https://github.com/amachanic/sp_whoisactive
2. Created a project: # dotnet new sqlproj
3. Create the project file:

        <Project Sdk="MSBuild.Sdk.SqlProj/1.11.3">
            <PropertyGroup>
                <TargetFramework>netstandard2.0</TargetFramework>
                <SqlServerVersion>Sql150</SqlServerVersion>
                
            </PropertyGroup>
        
            <PropertyGroup>
                
            </PropertyGroup>
        
          <ItemGroup>
            <Content Include="who_is_active.sql" />
          </ItemGroup>
        
        </Project>

4. Tried to build:

        $ dotnet build
        Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
        Copyright (C) Microsoft Corporation. All rights reserved.
        
          Determining projects to restore...
          All projects are up-to-date for restore.
          Using package name db.common.sp_whoisactive and version 1.0.0
          Using SQL Server version Sql150
          Adding /home/amesh/git/db.common.sp_whoisactive/who_is_active.sql to the model
          Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
           ---> Microsoft.SqlServer.Dac.Model.DacModelException: Add or update objects failed due to the following errors:
        EXEC : error SQL71006: Only one statement is allowed per batch. A batch separator, such as 'GO', might be required between statements. [/home/amesh/git/db.common.sp_whoisactive/db.common.sp_whoisactive.csproj]
        EXEC : warning SQL70501: DML statements cannot be modeled. [/home/amesh/git/db.common.sp_whoisactive/db.common.sp_whoisactive.csproj]
        EXEC : error SQL71001: Cannot find element referenced by the supporting statement. [/home/amesh/git/db.common.sp_whoisactive/db.common.sp_whoisactive.csproj]
        EXEC : error SQL71001: Cannot find element referenced by the supporting statement. [/home/amesh/git/db.common.sp_whoisactive/db.common.sp_whoisactive.csproj]
        EXEC : error SQL71001: Cannot find element referenced by the supporting statement. [/home/amesh/git/db.common.sp_whoisactive/db.common.sp_whoisactive.csproj]
        ...
        
             at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.ThrowIfModelErrorsExist(String errorMessage)
             at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.DoAddOrUpdateObjects(String inputScript, String sourceName, TSqlObjectOptions options)
             at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.AddOrUpdateObjects(String inputScript, String sourceName, TSqlObjectOptions options)
             at Microsoft.SqlServer.Dac.Model.TSqlModel.AddOrUpdateObjects(String inputScript, String sourceName, TSqlObjectOptions options)
             at MSBuild.Sdk.SqlProj.DacpacTool.PackageBuilder.AddInputFile(FileInfo inputFile) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/PackageBuilder.cs:line 85
             at MSBuild.Sdk.SqlProj.DacpacTool.Program.BuildDacpac(BuildOptions options) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Program.cs:line 122
             --- End of inner exception stack trace ---
             at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
             at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
             at System.Delegate.DynamicInvokeImpl(Object[] args)
             at System.Delegate.DynamicInvoke(Object[] args)
             at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
             at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
          --- End of stack trace from previous location ---
             at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
          --- End of stack trace from previous location ---
             at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
          --- End of stack trace from previous location ---
             at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
          --- End of stack trace from previous location ---
             at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
          --- End of stack trace from previous location ---
             at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
          --- End of stack trace from previous location ---
             at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
          --- End of stack trace from previous location ---
             at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
          --- End of stack trace from previous location ---
             at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
          --- End of stack trace from previous location ---
             at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
        /home/amesh/.nuget/packages/msbuild.sdk.sqlproj/1.11.3/Sdk/Sdk.targets(196,5): error MSB3073: The command "dotnet "/home/amesh/.nuget/packages/msbuild.sdk.sqlproj/1.11.3/Sdk/../tools/netcoreapp5.0/DacpacTool.dll" build -o "obj/Debug/netstandard2.0/db.common.sp_whoisactive.dacpac" -n "db.common.sp_whoisactive" -v "1.0.0" -sv Sql150 -i "obj/Debug/netstandard2.0/db.common.sp_whoisactive.InputFiles.txt"       " exited with code 1. [/home/amesh/git/db.common.sp_whoisactive/db.common.sp_whoisactive.csproj]
        
        Build FAILED.

Changing 'Content' to 'None' did not produce a difference.
How do I make this work?

**Comment by jeffrosenberg** [comment]
@artazar a few thoughts:

1. The reason this doesn't work without modification is that the Microsoft DacFX framework, which our project is based upon, expects a particular DDL syntax. All objects should be expressed as `CREATE` statements, in their own batch. You can achieve this by removing the first 11 lines (those properties can be set on your .csproj file, see our readme), and changing the `ALTER PROC` on line 24 to `CREATE PROC`.

2. If you go that route, your `Content` node shouldn't be necessary. All .sql files are included in the database model automatically, so the `Content` node is really only needed once you want to start excluding files from the project.

3. Another option, if you wanted to treat this as just a script to execute, rather than as DDL, you could change your `Content` node to `<Content Remove="who_is_active.sql" />`. This will fix the error, but you won't actually produce a .dacpac artifact with any contents, you'll just have the script.

4. To that point, I want to clarify the purpose of this project. The intention is to use the DacFX framework to allow you to build databases out of multiple schema files, then use the resulting artifact to deploy them to target servers with migration scripts that are auto-generated in real time by Microsoft tooling (most often the SqlPackage utility). The .csproj file you're showing here would result in a separate database with just this single stored procedure, not sure if that's what you're after.

**Comment by artazar** [comment]
Hi @jeffrosenberg ,

Appreciate your time and a detailed response!

I was investigating the possibilities of packing particular common scripts into dacpac packages similarly to what's described here: https://the.agilesql.club/2015/10/dir2dac-and-github2dacpac-create-dacpacs-from-script-folders-or-the-internet/

But as you explained, by design, this cannot be a pack of scripts, but rather a fully crafted master database baked into a dacpac. I will see how to properly form such flow into a pipeline.

**Comment by Shweta234** [comment]
@artazar Observing thesame issue. Can you please suggest how you have resolved it?
