### ISSUE TITLE
Can not recursively exclude files from build 

### ISSUE THREAD

**Issue by kijewskimateusz** [rr-wfm/MSBuild.Sdk.SqlProj#128]
Hello, 

It looks like it's impossible to add entire directory to exclude from build. Whenever I'm trying to exclude a folder containing more than one file with command `<Content Remove="Repos\*\Scripts\Inserts\*.sql" />`, it throws an error:

> ---> Microsoft.SqlTools.ServiceLayer.BatchParser.BatchParserException: Incorrect syntax was encountered while parsing '
>   '.
>      at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.RaiseError(ErrorCode errorCode, Token token, String message) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 621
>      at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.RaiseError(ErrorCode errorCode, String message) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 612
>      at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.Expect(LexerTokenType lexerTokenType) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 217
>      at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.ParseInclude() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 272
>      at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.ParseLines() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 394
>      at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.Parse() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 232
>      at MSBuild.Sdk.SqlProj.DacpacTool.ScriptParser.Parse() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptParser.cs:line 
> 27
>      at MSBuild.Sdk.SqlProj.DacpacTool.ScriptParser.CollectFileNames() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptParser.cs:line 34
>      at MSBuild.Sdk.SqlProj.DacpacTool.ScriptInspector.AddIncludedFiles(FileInfo file) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptInspector.cs:line 28
>      at MSBuild.Sdk.SqlProj.DacpacTool.Program.InspectIncludes(InspectOptions options) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Program.cs:line 149
>      --- End of inner exception stack trace ---
>      at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>      at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>      at System.Delegate.DynamicInvokeImpl(Object[] args)
>      at System.Delegate.DynamicInvoke(Object[] args)
>      at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
>      at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
>   --- End of stack trace from previous location ---
>      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
>   --- End of stack trace from previous location ---
>      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
>   --- End of stack trace from previous location ---
>      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
>   --- End of stack trace from previous location ---
>      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
>   --- End of stack trace from previous location ---
>      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
>   --- End of stack trace from previous location ---
>      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
>   --- End of stack trace from previous location ---
>      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
>   --- End of stack trace from previous location ---
>      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
>   --- End of stack trace from previous location ---
>      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by kijewskimateusz** [comment]
Attached you can find file system causing an error 
![image](https://user-images.githubusercontent.com/65126185/115772751-c4207d80-a3af-11eb-83e0-1f16476d84e8.png)

**Comment by jmezach** [comment]
@kijewskimateusz Thanks for reporting. Have you tried using a double * instead of a single one? So for example `<Content Remove="Repos\**\Scripts\Inserts\*.sql" />`? I think that is the syntax you need when you want to include subfolders.

If that doesn't help, please share the entire output of `dotnet build` so we can further diagnose the issue.

**Comment by kijewskimateusz** [comment]
Hello, sorry for the significant delay while getting back to you. Unfortunately, the issue still persists, when I'm using doubled **. I've also found out that the issue only happens when allocating items to be excluded within subdirectories. They are recursively selected while stored within the main directory.
Attached you'll find my copy of the output window, unfortunately in Polish, but also I've prepared you sample repository with a solution for easy defect replication here - https://github.com/kijewskimateusz/SQL-CICD-Solution.git

```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MBP-Kamila:SQL-CICD-Solution Kamila$ dotnet build
Microsoft (R) Build Engine 16.9.0+57a23d249 dla platformy .NET
Copyright (C) Microsoft Corporation. Wszelkie prawa zastrzeżone.

  Trwa określanie projektów do przywrócenia...
  Wszystkie projekty są aktualne na potrzeby przywrócenia.
  Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> Microsoft.SqlTools.ServiceLayer.BatchParser.BatchParserException: Incorrect syntax was encountered while parsing '
  '.
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.RaiseError(ErrorCode errorCode, Token token, String message) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 621
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.RaiseError(ErrorCode errorCode, String message) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 612
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.Expect(LexerTokenType lexerTokenType) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 217
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.ParseInclude() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 272
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.ParseLines() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 394
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.Parse() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 232
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptParser.Parse() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptParser.cs:line 27
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptParser.CollectFileNames() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptParser.cs:line 34
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptInspector.AddIncludedFiles(FileInfo file) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptInspector.cs:line 28
     at MSBuild.Sdk.SqlProj.DacpacTool.Program.InspectIncludes(InspectOptions options) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Program.cs:line 149
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Delegate.DynamicInvokeImpl(Object[] args)
     at System.Delegate.DynamicInvoke(Object[] args)
     at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
     at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
/Users/Kamila/.nuget/packages/msbuild.sdk.sqlproj/1.11.4/Sdk/Sdk.targets(163,5): error MSB3073: Polecenie „...” zostało zakończone przez kod 1. [/Users/Kamila/Mateusz/SQL-CICD-Solution/dotnet build.csproj]

Kompilacja NIE POWIODŁA SIĘ.

/Users/Kamila/.nuget/packages/msbuild.sdk.sqlproj/1.11.4/Sdk/Sdk.targets(163,5): error MSB3073: Polecenie „...” zostało zakończone przez kod 1. [/Users/Kamila/Mateusz/SQL-CICD-Solution/dotnet build.csproj]
    Ostrzeżenia: 0
    Liczba błędów: 1

Czas, który upłynął: 00:00:02.05```

**Comment by jmezach** [comment]
After having looked at the stacktrace it seems this is failing in the calculation of files that are included from the pre- and post-deployment scripts. You'll want to look at `Pre-Deployment\Script.PreDeployment.sql` and `Post-Deployment\Script.PostDeployment.sql` and see what's included from there (using the `:r <file>.sql` syntax) to figure out where the error is coming from.

@jeffrosenberg We should probably improve the diagnostics here. I think we should at least provide a pointer to the file where things are failing. If I remember correctly you've added this feature. Do you see any possibilities to do that?

**Comment by kijewskimateusz** [comment]
Hello,

After tweaking PostDeployment file I confirm that it's working. It was an error on my side, but I agree that error messages are quite difficult to understand for someone not working with dotnet 

Thanks!

**Comment by jeffrosenberg** [comment]
@jmezach looking briefly at the code, unfortunately I think that's largely managed in the `BatchParser` submodule, rather than our own code. This is the entirety of the code captured by our own code in the stacktrace:

```c#
private void Parse()
{
    if (! _parsed)
    {
        _parser.Parse();
        _parsed = true;
    }
}

public IEnumerable<string> CollectFileNames()
{
    Parse();
    return _includedFileNames;
}
```

This is a common gripe at my workplace, too, and has been since the .sqlproj days -- to the point that we've started prefixing every included file with a `PRINT` line with the included filename to help improve troubleshooting.

Given what a pain this is, I'm happy to look at it further in the next few days. Maybe at the very least, if I can't find a way to fix the problem, I can add a warning about the issue to the readme, perhaps with the recommendation of the workaround my team uses? It's no substitute for a proper exception, but if it's all we can do it's better than nothing.
