### ISSUE TITLE
Using SqlCmdVariable and GenerateCreateScript property failed on build

### ISSUE THREAD

**Issue by Condor2708** [rr-wfm/MSBuild.Sdk.SqlProj#201]
```
1>------ Rebuild All started: Project: Kapsch.Internationalization.Database.MVP, Configuration: Debug Any CPU ------
Restored C:\dev-net5\platform-mvp\culture\src\mvp\Kapsch.CultureManager.MVP\Kapsch.CultureManager.MVP.csproj (in 938 ms).
1>Using package name Kapsch.Internationalization.Database.MVP and version 7.0.0.1
1>Using SQL Server version Sql150
1>Adding reference to C:\Users\sanchez\.nuget\packages\kapsch.internationalization.database\7.0.0.6/tools/Kapsch.Internationalization.Database.dacpac with external parts dbl=|dbv=|srv=
1>Adding SqlCmd variable KTC_DefaultDataPath
1>Writing model to C:\dev-net5\platform-mvp\culture\src\mvp\Kapsch.Internationalization.Database.MVP\obj\Debug\netstandard2.0\Kapsch.Internationalization.Database.MVP.dacpac
1>Adding C:\dev-net5\platform-mvp\culture\src\mvp\Kapsch.Internationalization.Database.MVP\Scripts\Script.PreDeployment.sql to package
1>Adding C:\dev-net5\platform-mvp\culture\src\mvp\Kapsch.Internationalization.Database.MVP\Scripts\Script.PostDeployment.sql to package
1>Generating create script Kapsch.Internationalization.Database.MVP_Create.sql
1>Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
1> ---> Microsoft.SqlServer.Dac.DacServicesException: An error occurred during deployment plan generation. Deployment cannot continue.
1> ---> Microsoft.Data.Tools.Schema.Sql.Deployment.DeploymentFailedException: Missing values for the following SqlCmd variables:KTC_DefaultDataPath.
1>   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment.CheckSqlCmdVariables(HashSet`1 expectedVariables, Dictionary`2 actualVariables, DataSchemaError& unusedVariableWarning)
1>   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment.VerifySqlCmdVariables()
1>   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment.PerformDeploymentChecksThatRequireModels()
1>   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment.InitializePlanGeneratator()
1>   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment.CreateController(Action`1 msgHandler)
1>   at Microsoft.SqlServer.Dac.DacServices.CreateController(SqlDeployment deploymentEngine, ErrorManager errorManager)
1>   --- End of inner exception stack trace ---
1>   at Microsoft.SqlServer.Dac.DacServices.CreateController(SqlDeployment deploymentEngine, ErrorManager errorManager)
1>   at Microsoft.SqlServer.Dac.DacServices.<>c__DisplayClass44_0.<CreateDeploymentArtifactGenerationOperation>b__0(Object operation, CancellationToken token)
1>   at Microsoft.SqlServer.Dac.Operation.Microsoft.SqlServer.Dac.IOperation.Run(OperationContext context)
1>   at Microsoft.SqlServer.Dac.ReportMessageOperation.Microsoft.SqlServer.Dac.IOperation.Run(OperationContext context)
1>   at Microsoft.SqlServer.Dac.OperationExtension.Execute(IOperation operation, DacLoggingContext loggingContext, CancellationToken cancellationToken)
1>   at Microsoft.SqlServer.Dac.DacServices.GenerateCreateScript(Stream outputStream, DacPackage package, String targetDatabaseName, DacDeployOptions options)
1>   at MSBuild.Sdk.SqlProj.DacpacTool.PackageBuilder.GenerateCreateScript(FileInfo dacpacFile, String databaseName) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/PackageBuilder.cs:line 401
1>   at MSBuild.Sdk.SqlProj.DacpacTool.Program.BuildDacpac(BuildOptions options) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Program.cs:line 167
1>   --- End of inner exception stack trace ---
1>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
1>   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>   at System.Delegate.DynamicInvokeImpl(Object[] args)
1>   at System.Delegate.DynamicInvoke(Object[] args)
1>   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
1>   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
1>C:\Users\sanchez\.nuget\packages\msbuild.sdk.sqlproj\1.16.2\Sdk\Sdk.targets(227,5): error MSB3073: The command "dotnet "C:\Users\sanchez\.nuget\packages\msbuild.sdk.sqlproj\1.16.2\Sdk\../tools/netcoreapp5.0/DacpacTool.dll" build -o "obj\Debug\netstandard2.0\Kapsch.Internationalization.Database.MVP.dacpac" -n "Kapsch.Internationalization.Database.MVP" -v "7.0.0.1" -sv Sql150 -i "obj\Debug\netstandard2.0\Kapsch.Internationalization.Database.MVP.InputFiles.txt" -r "C:\Users\sanchez\.nuget\packages\kapsch.internationalization.database\7.0.0.6/tools/Kapsch.Internationalization.Database.dacpac;dbl=|dbv=|srv=" -sc KTC_DefaultDataPath  --predeploy Scripts\Script.PreDeployment.sql --postdeploy Scripts\Script.PostDeployment.sql      --generatecreatescript" exited with code 1.
1>Done building project "Kapsch.Internationalization.Database.MVP.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by jmezach** [comment]
This is probably because we don't currently pass in the values of SQLCMD variables during `dotnet build`, but only during `dotnet publish`. Probably isn't too hard to change, so feel free to submit a PR.

**Comment by fpucheta** [comment]
@jmezach Hi! Do you have any idea about when will this will be resolved? I have #204 opened that's related, and unfortunately I don't have enough experience to fix it by my own. Thanks!

**Comment by jmezach** [comment]
@fpucheta I'm quite busy with my regular day job at the moment so I don't think I'll have time to implement this any time soon. Maybe @jeffrosenberg or @ErikEJ have some spare time to implement this, but please keep in mind that we all have our own lives.

**Comment by fpucheta** [comment]
@jmezach Thanks. Yes, I know you are doing a great job with this project and it's a great contribution to the community, and that you guys do that in your free time, it's just that as I don't know how you manage this, just wondered if you may have some tasks/fixes scheduled, but of course, always asking with my best intention.

**Comment by ErikEJ** [comment]
@fpucheta Can you share a repro project?

**Comment by ErikEJ** [comment]
@Condor2708 Can you share a repro project (sorry @fpucheta )

**Comment by fpucheta** [comment]
@ErikEJ If there's no answer from the creator of this issue, I created issue [#204](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/204) that's related to this one, just in case you can use the project I share there to test this.

**Comment by ErikEJ** [comment]
@fpucheta In #204 it seems you talk about `dotnet publish` issues?

In that case, we always recommend using the dotnet tool `microsoft.sqlpackage` for publishing, not `dotnet publish` which is aimed at local development convenience.

It is very easy to install and use the dotnet tool from a pipeline, as you can see in main.yml in this repo.

**Comment by ErikEJ** [comment]
@fpucheta Could you try 2.0.4 which now includes the default values for SQLCMD variables in the generated .dacpac?

**Comment by fpucheta** [comment]
@ErikEJ Sure, I'll test it as soon as possible and will let you know. Thanks!

**Comment by ErikEJ** [comment]
@fpucheta Any updates?
