### ISSUE TITLE
Running dotnet build -o failed with MSBuild.Sdk.Sqlproj/2.0.0-beta.1 and dotnet sdk 6.0.100

### ISSUE THREAD

**Issue by Condor2708** [rr-wfm/MSBuild.Sdk.SqlProj#235]
Hi all,

When i changed to dotnet 6 and MSBuild.Sdk.Sqlproj/2.0.0-beta.1, I found that when I try to use dotnet build -o option with a different output folder fails with the following error:

```
dotnet build "./src/mvp/Security.Database.MVP/Security.Database.MVP.csproj" -c Release -o c:\tmp\sec

...
...
..

proj".
   1:7>Target "GenerateNuspec" in file "C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets" from project "C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\Security.Database.MVP.csproj" (target "Pack" depends on it):
       Building target "GenerateNuspec" completely.
       Output file "c:\tmp\sec\Security.Database.MVP.7.1.0.nupkg" does not exist.
       Task "ConvertToAbsolutePath"
       Done executing task "ConvertToAbsolutePath".
       Using "PackTask" task from assembly "C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\build\..\CoreCLR\NuGet.Build.Tasks.Pack.dll".
       Task "PackTask"
   1:7>C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error : Could not find a part of the path 'C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\bin\Release\netstandard2.0'. [C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\Security.Database.MVP.csproj]
         System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\bin\Release\netstandard2.0'.
            at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
            at System.IO.Enumeration.FileSystemEnumerator`1.Init()
            at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
            at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
...
...

Build FAILED.

       "C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\Security.Database.MVP.csproj" (default target) (1:7) ->
       (GenerateNuspec target) ->
         C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error : Could not find a part of the path 'C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\bin\Release\netstandard2.0'. [C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\Security.Database.MVP.csproj]

    0 Warning(s)
    1 Error(s)
```

If i remove the -o option it works ok

```
 dotnet build "./src/mvp/Security.Database.MVP/Security.Database.MVP.csproj" -c Release
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Using target framework net6.0 to run DacpacTool
  Using package name Security.Database.MVP and version 7.1.0
  Using SQL Server version Sql150
  Adding reference to C:\Users\sanchez\.nuget\packages\security.database\7.1.0/tools/Security.Database.dacpac with external parts dbl=|dbv=|srv=
  Adding SqlCmd variable KTC_DefaultDataPath
  Writing model to C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\obj\Release\netstandard2.0\Security.Database.MVP.dacpac
  Adding C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\Pre-Deployment\Script.PreDeployment.sql to package
  Adding C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\Post-Deployment\Script.PostDeployment.sql to package
  Security.Database.MVP -> C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\bin\Release\netstandard2.0\Security.Database.MVP.dacpac
  Successfully created package 'C:\git\v3.1.0\platform-mvp\security\src\mvp\Security.Database.MVP\bin\Release\Security.Database.MVP.7.1.0.nupkg'.

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

Anyone is having this issue or knows how to fix it ?

Thanks !! Santiago

**Comment by Condor2708** [comment]
I found out that if i change the bin folder with the obj folder in my nuspec file it worked... but i don't know if this is the expected behaviour

```
 <files>
    <file src="bin\$configuration$\$tfm$\*.dacpac" target="tools/" />
  </files>

obj folder instead of bin

 <files>
    <file src="obj\$configuration$\$tfm$\*.dacpac" target="tools/" />
  </files>
```

**Comment by jmezach** [comment]
Looks like your `.nuspec` file assumes that the `.dacpac` is in the bin folder, but obviously that changes if you use the `-o` option since it will redirect the output elsewhere. So yeah, I would say that this is the expected behaviour.

**Comment by greektreat** [comment]
@Condor2708 , Where do you find the details how to set this up in .net 6, I've tried changing it the project file 
from  <Project Sdk="MSBuild.Sdk.SqlProj/1.15.0">
to: <Project Sdk="MSBuild.Sdk.Sqlproj/2.0.0-beta">
and it unloaded the project because it wasn't valid project file any more

**Comment by jmezach** [comment]
Feel free to re-open if this is still an issue.
