### ISSUE TITLE
Error MSB3073: The command "..." exited with code 1

### ISSUE THREAD

**Issue by RubenDelange** [rr-wfm/MSBuild.Sdk.SqlProj#264]
When doing a 'dotnet build' within an Azure DevOps yaml pipeline having `vmImage: 'ubuntu-latest'`, I get the following error : 

`[error]/home/vsts/.nuget/packages/msbuild.sdk.sqlproj/2.0.0/Sdk/Sdk.targets(168,5): Error MSB3073: The command "..." exited with code 1.`

I don't get any errors when I run a local 'dotnet build', so I don't know what's going on. Any feedback or pointers are more than welcome!

tia!

edit: using `<Project Sdk="MSBuild.Sdk.SqlProj/2.0.0-beta.1">` gives the same error
edit2: when I use `vmImage: 'windows-latest'`, everything works as expected

edit3: I overlooked the actual error :
```
System.IO.FileNotFoundException: Could not find file '/home/vsts/work/1/s/<my db project>/Post-Deployment/.\00_insert_masterdata.sql'.
 File name: '/home/vsts/work/1/s/<my db project>/Post-Deployment/.\00_insert_masterdata.sql'
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
     at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
     at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
     at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
     at System.IO.StreamReader..ctor(String path)
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptParser.Microsoft.SqlTools.ServiceLayer.BatchParser.ICommandHandler.Include(TextBlock includeBlock, TextReader& stream, String& newFilename) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptParser.cs:line 77
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.ParseInclude() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 302
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.ParseLines() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 394
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.Parse() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 232
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptParser.Parse() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptParser.cs:line 30
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptParser.CollectFileNames() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptParser.cs:line 47
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptInspector.AddIncludedFiles(FileInfo file) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptInspector.cs:line 28
     at MSBuild.Sdk.SqlProj.DacpacTool.Program.InspectIncludes(InspectOptions options) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Program.cs:line 184
```

this smells like a bug?

**Comment by jeffrosenberg** [comment]
@RubenDelange do you have a reference to one or more files using backslashes? That's my guess based on the message `Could not find file '/home/vsts/work/1/s/<my db project>/Post-Deployment/.\00_insert_masterdata.sql'`.

Backslashes won't work on Linux, however forward slashes _will_ work on Windows. If I'm right that you're using backslashes in your paths, try using forward slashes and let us know if that resolves the issue.

**Comment by RubenDelange** [comment]
Hi @jeffrosenberg , of course, backslashes! I removed the .\ statements in the post-deployment script (cfr. generated example code lol), all is good now.

Thank you for your quick reply!
