### ISSUE TITLE
Referencing Microsoft.SqlServer.Dacpacs.Master fails

### ISSUE THREAD

**Issue by marcadella** [rr-wfm/MSBuild.Sdk.SqlProj#483]
Following the doc, I added the following line to my project file:
`<PackageReference Include="Microsoft.SqlServer.Dacpacs.Master" Version="150.0.0" DacpacName="master" />`
But when doing so, I get the following error when running `dotnet build`:
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlScriptDomGenerator.CreateStatementGenerator.GenerateCreateAggregateStatement(IModelElement modelElement)
     at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlScriptDomGenerator.CreateStatementGenerator.GenerateStatement(IModelElement modelElement)
     at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlScriptDomGenerator.TryGenerateScriptDom(IModelElement element, ScriptDomOperation operation, TSqlScript& script)
     at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlScriptDomGenerator.GenerateScriptDom(IModelElement element, ScriptDomOperation operation)
     at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeploymentPlanGenerator.DeploymentScriptDomGenerator.GenerateFragment(Int32 operation, IModelElement element)
     at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeploymentPlanGenerator.DeploymentScriptDomGenerator.GenerateSteps(Int32 operation, IModelElement element)
     at Microsoft.Data.Tools.Schema.Sql.Deployment.OrderedStepGenerator.Add(DeploymentScriptDomGenerator scriptDom, IModelElement element, Int32 operation)
     at Microsoft.Data.Tools.Schema.Sql.Deployment.Analyzers.PlanMediator.BuildDependencyOrderedSteps(Int32 operation, List`1 classOrder, List`1 operationOrder, Dictionary`2 changes, Boolean preserveGraphs, Dictionary`2& relating, Dicti
  onary`2& related)
     at Microsoft.Data.Tools.Schema.Sql.Deployment.Analyzers.PlanMediator.BuildOperations()
     at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeploymentPlanGenerator.OnGeneratePlan()
     at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeploymentPlanGenerator.GeneratePlan(List`1 drops)
     at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment.BuildPlan()
     at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlDeployment.Controller.CreatePlan()
     at Microsoft.SqlServer.Dac.DacServices.<>c__DisplayClass53_0.<CreateDeploymentArtifactGenerationOperation>b__0(Object operation, CancellationToken token)
     at Microsoft.SqlServer.Dac.Operation.Microsoft.SqlServer.Dac.IOperation.Run(OperationContext context)
     at Microsoft.SqlServer.Dac.ReportMessageOperation.Microsoft.SqlServer.Dac.IOperation.Run(OperationContext context)
     at Microsoft.SqlServer.Dac.OperationExtension.Execute(IOperation operation, DacLoggingContext loggingContext, CancellationToken cancellationToken)
     at Microsoft.SqlServer.Dac.DacServices.GenerateCreateScript(Stream outputStream, DacPackage package, String targetDatabaseName, DacDeployOptions options)
     at MSBuild.Sdk.SqlProj.DacpacTool.PackageBuilder.GenerateCreateScript(FileInfo dacpacFile, String databaseName, DacDeployOptions deployOptions) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/PackageBuil
  der.cs:line 389
     at MSBuild.Sdk.SqlProj.DacpacTool.Program.BuildDacpac(BuildOptions options) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Program.cs:line 189
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
     --- End of inner exception stack trace ---
     at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Delegate.DynamicInvokeImpl(Object[] args)
     at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
     at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
.\.nuget\packages\msbuild.sdk.sqlproj\2.6.1\Sdk\Sdk.targets(242,5): error MSB3073: The command "dotnet ".\.nuget\packages\msbuild.sdk.sqlproj\2.6.1\Sdk\../tools/net7.0/DacpacTool.dll" build -o "obj\
Debug\netstandard2.0\prodreg-sql.dacpac" -n "prodreg-sql" -v "1.0.0" -sv Sql150 -i "obj\Debug\netstandard2.0\prodreg-sql.InputFiles.txt" -r ".\.nuget\packages\microsoft.sqlserver.dacpacs.master\150.0.0/tools/master.da
cpac;dbl=|dbv=|srv=;" -r ".\.nuget\packages\microsoft.sqlserver.dacpacs.msdb\150.0.0/tools/msdb.dacpac;dbl=|dbv=|srv=;"   -dp IncludeCompositeObjects=True        --generatecreatescript " exited with code 1. [.\IdeaProjects\LDF\prodreg-sql\prodreg-sql.csproj]
```

Any idea of what can be the issue here?

**Comment by cagrin** [comment]
Same problem here on dotnet publish: "Object reference not set to an instance of an object."

**Comment by cagrin** [comment]
I've been trying to prepare decent example code, but I've figured it out that somehow adding `DatabaseVariableLiteralValue="master"` helps:

`<PackageReference Include="Microsoft.SqlServer.Dacpacs.Master" Version="150.0.0" DacpacName="master" DatabaseVariableLiteralValue="master"/>`

@marcadella - please, try it and let us know.

**Comment by ErikEJ** [comment]
@marcadella Ping?

**Comment by marcadella** [comment]
Didn't work for me. I gave up trying to include external libraries.

**Comment by ErikEJ** [comment]
@marcadella Can you share your .csproj?

Looks like you are using GenerateCreateScript.

Maybe try <IncludeCompositeObjects>False</IncludeCompositeObjects>

**Comment by ErikEJ** [comment]
Closing as no reply provided
